# Generated by Django 6.0.2 on 2026-02-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('planned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('planned_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('brought_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('returned_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.saleschannel')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.cropsalesformat')),
            ],
            options={
                'ordering': ['sale_date', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='QuickSalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.saleschannel')),
            ],
            options={
                'ordering': ['sale_date', 'channel'],
                'unique_together': {('channel', 'sale_date')},
            },
        ),
    ]
