# Generated by Django 6.0.2 on 2026-02-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_family', models.CharField(max_length=50, unique=True)),
                ('min_gap_years', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GrowingSeasonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('week', models.PositiveIntegerField()),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['year', 'week'],
                'unique_together': {('year', 'week', 'event_date')},
            },
        ),
        migrations.CreateModel(
            name='RotationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('botanical_family', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_history', to='reference.block')),
            ],
            options={
                'ordering': ['block__name', '-year'],
                'unique_together': {('block', 'year')},
            },
        ),
    ]
