# Generated by Django 6.0.2 on 2026-02-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("field", "Field"),
                            ("high_tunnel", "High Tunnel"),
                            ("greenhouse", "Greenhouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("num_beds", models.PositiveIntegerField()),
                ("bed_width_feet", models.DecimalField(decimal_places=1, max_digits=4)),
                ("bedfeet_per_bed", models.PositiveIntegerField()),
                ("walk_route_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["walk_route_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CropInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("crop_type", models.CharField(max_length=50)),
                ("botanical_family", models.CharField(blank=True, max_length=50)),
                (
                    "propagation_type",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("vegetative_clove", "Clove"),
                            ("vegetative_tuber", "Tuber"),
                            ("vegetative_slip", "Slip"),
                        ],
                        default="seed",
                        max_length=20,
                    ),
                ),
                ("is_perennial", models.BooleanField(default=False)),
                (
                    "fresh_or_storage",
                    models.CharField(
                        choices=[("fresh", "Fresh"), ("storage", "Storage")],
                        max_length=10,
                    ),
                ),
                ("storage_weeks", models.PositiveIntegerField(default=0)),
                ("harvest_unit", models.CharField(max_length=20)),
                (
                    "avg_unit_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("units_per_bin", models.PositiveIntegerField(blank=True, null=True)),
                ("harvest_bin", models.CharField(blank=True, max_length=50)),
                ("harvest_tools", models.CharField(blank=True, max_length=100)),
                (
                    "harvest_rate_per_hour",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("nursery_weeks", models.PositiveIntegerField(default=0)),
                ("weeks_until_pot_up", models.PositiveIntegerField(default=0)),
                (
                    "pot_up_tray_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "seeded_tray_size",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("seeds_per_cell", models.PositiveIntegerField(default=1)),
                ("thinned_plants", models.PositiveIntegerField(default=0)),
                (
                    "seeds_per_ounce",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CropByseason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("field", "Field"),
                            ("high_tunnel", "High Tunnel"),
                            ("greenhouse", "Greenhouse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_week_start", models.PositiveIntegerField()),
                ("field_week_end", models.PositiveIntegerField()),
                (
                    "total_yield_per_bedfoot",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("harvest_weeks", models.PositiveIntegerField()),
                ("dtm_days", models.PositiveIntegerField()),
                ("rows_per_bed", models.PositiveIntegerField()),
                ("ds_seed_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tp_inrow_spacing",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("seeder_settings", models.CharField(blank=True, max_length=200)),
                ("trellis_system", models.CharField(blank=True, max_length=100)),
                ("mulch", models.CharField(blank=True, max_length=50)),
                ("row_cover", models.CharField(blank=True, max_length=50)),
                ("irrigation", models.CharField(blank=True, max_length=50)),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_profiles",
                        to="reference.cropinfo",
                    ),
                ),
            ],
            options={
                "ordering": ["crop__name", "block_type"],
                "unique_together": {("crop", "block_type")},
            },
        ),
    ]
