# Generated by Django 6.0.2 on 2026-02-26 01:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('complete', 'Complete'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('overplant_factor', models.DecimalField(decimal_places=2, default=Decimal('1.10'), max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succession_group', models.CharField(blank=True, max_length=50)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('bed_start', models.PositiveIntegerField()),
                ('bed_end', models.PositiveIntegerField()),
                ('planned_bedfeet', models.PositiveIntegerField()),
                ('planned_plant_date', models.DateField()),
                ('planned_first_harvest_date', models.DateField()),
                ('planned_last_harvest_date', models.DateField()),
                ('planned_total_yield', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_bedfeet', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_plant_date', models.DateField(blank=True, null=True)),
                ('actual_first_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_last_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_total_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('seeded', 'Seeded (nursery)'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvesting', 'Harvesting'), ('complete', 'Complete'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('revised', 'Revised')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.block')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.cropinfo')),
                ('crop_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.cropbyseason')),
                ('planning_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantings', to='planning.planningyear')),
                ('revision_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='planning.planting')),
            ],
            options={
                'ordering': ['planned_plant_date', 'block__name'],
            },
        ),
        migrations.CreateModel(
            name='NurseryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('seed', 'Seed'), ('pot_up', 'Pot Up'), ('harden', 'Harden Off'), ('transplant', 'Transplant')], max_length=20)),
                ('planned_date', models.DateField()),
                ('planned_tray_count', models.PositiveIntegerField(blank=True, null=True)),
                ('planned_tray_size', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('actual_tray_count', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_tray_size', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_germination_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursery_events', to='planning.planting')),
            ],
            options={
                'ordering': ['planned_date', 'planting'],
            },
        ),
        migrations.CreateModel(
            name='HarvestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planned_units', models.CharField(max_length=20)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_units', models.CharField(blank=True, max_length=20)),
                ('actual_bins', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('actual_bin_type', models.CharField(blank=True, max_length=50)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('actual_workers', models.PositiveIntegerField(blank=True, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('prime', 'Prime'), ('seconds', 'Seconds'), ('mixed', 'Mixed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_events', to='planning.planting')),
            ],
            options={
                'ordering': ['planned_date', 'planting'],
            },
        ),
    ]
