# Generated by Django 6.0.2 on 2026-02-26 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planning', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWalkNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walk_date', models.DateField()),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('failed', 'Failed')], max_length=10)),
                ('adjusted_first_harvest_date', models.DateField(blank=True, null=True)),
                ('adjusted_last_harvest_date', models.DateField(blank=True, null=True)),
                ('yield_adjust_pct', models.PositiveIntegerField(default=100, help_text='100 = no change, 50 = half expected yield')),
                ('notes', models.TextField(blank=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_walk_notes', to='planning.planting')),
            ],
            options={
                'ordering': ['-walk_date', 'planting__block__walk_route_order'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(choices=[('harvest_in', 'Harvest In'), ('sale_out', 'Sale Out'), ('return_in', 'Return In'), ('waste_out', 'Waste Out'), ('transfer', 'Transfer'), ('quality_check', 'Quality Check'), ('year_end_count', 'Year End Count'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.cropinfo')),
                ('harvest_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.harvestevent')),
            ],
            options={
                'ordering': ['crop__name', 'event_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.saleschannel')),
                ('harvest_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_allocations', to='planning.harvestevent')),
                ('inventory_draw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.inventoryledger')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.cropsalesformat')),
            ],
            options={
                'ordering': ['pack_date', 'channel__allocation_priority'],
            },
        ),
    ]
